### ISSUE TITLE
Developement resumed ? 

### ISSUE THREAD

**Issue by mistajuliax** [UPBGE/blender#1042]
So developement resumed ? project has new developers ?? or is it totally stopped ? 
Cheers.

**Comment by UglinessInTheUI** [comment]
Yeah. It's resumed for sure. With tons of new developers. Included.

**Comment by marechal-p** [comment]
Not really sure if @UglinessInTheUI is being sarcastic, but there are some people tentatively trying to address some issues.

Namely @UnidayStudio and @BluePrintRandom. But focus on development is not easy to maintain, has it is really time consuming and people often prefer being users rather than devs.

Until proven otherwise I would consider the development stopped.

Pull requests are welcome though :)

**Comment by mistajuliax** [comment]
I'm used to some sarcastic answers from childish teenagers. It's not a problem. I saw the new upbge site that's why i asked for ... anyway, thanks for replying @marechal-p

**Comment by UglinessInTheUI** [comment]
LOL
