### ISSUE TITLE
no compatible gpu found

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#1052]
Hi Guys , 
With the last build of upbge ,in the preference panel can't found my GPU

i have an nVidia GTX 1050 TI with the last updated drivers

is it normal ?

Thanks

![no_compatible_gpu](https://user-images.githubusercontent.com/20901566/61567929-9a6f4f80-aa81-11e9-9532-2f23d3936b10.png)

**Comment by youle31** [comment]
Yeah, I think it is normal because we've never build with cuda (because it's not enabled by default and we forgot it). It is an option to enable in cmake before building. It is used with cycles. If you build, in cmake, you can enable it

![Capture](https://user-images.githubusercontent.com/10052509/61569437-9fcf9880-aa87-11e9-9e25-887c7771c771.PNG)

**Comment by RomStef** [comment]
Can i have better performance using cuda ?

**Comment by youle31** [comment]
Cuda is only for cycles rendering with nvidia GPUs. This is not related to bge drawing

**Comment by RomStef** [comment]
ok then i can close this issue. thanks
