### ISSUE TITLE
Remove 2.80 discussions from UPBGE git

### ISSUE THREAD

**Issue by shuvit-game** [UPBGE/blender#1066]
The experimental branches of 2.8 do not belong within the UPBGE project. It is not a game engine. It is not a part of the original project. In fact it's goals are polar opposites. The discussions here greatly distracts from finding and fixing real issues with the UPBGE game engine.

**Comment by BluePrintRandom** [comment]
I am pretty sure without loki and youle master would not even build right now.

their work is going to be upbge 0.3.0 

if you want to submit pull requests for 0.2.5 that is fine.

I think this "legacy vs current" debate would be best solved by patches or silence.

**Comment by shuvit-game** [comment]
Their work on 2.8 should not be considered part of UPBGE for reasons I have previously stated. To call it such is destroying the good name of the UPBGE project and making their communities inhabitable for people with current UPBGE projects. If you want to find your own home for your new project, that is fine.

**Comment by BluePrintRandom** [comment]
I think the ubge project is defined by the will of it's active developers

your are free to fork the project*

**Comment by shuvit-game** [comment]
> their work is going to be upbge 0.3.0

> I think the ubge project is defined by the will of it's active developers

Is there anyone sober who would like to comment on this issue?

**Comment by lordloki** [comment]
Please stop. This protest makes no sense.

When Blender was released at 2.26 there was no possibility to continue using his SUMO collision library. Then several options arose until they decided to use Bullet. Do you think the 2.26 or 2.27 BGE was not the real BGE? It was simply the same game engine using another collision library. The physical reactions of the elements were not exactly the same as before but people got used to the new collision library.

This is exactly the same but it affects the rendering library and the dependency graph. The engine is still BGE/UPBGE but it has to evolve. Users will have to adapt again, if they want (and I really really want that they can adapt and enjoy the new possibilities). It's a law of life. 

As we spoke a month ago I have neither the knowledge nor the time to acquire such knowledge necessary to continue the work done by @panzergame . Therefore, we need to evolve. The easiest way is to use Eevee / depsgraph since it will be actively maintained by other people. We will also have the advantage of being able to keep up to date with Blender (The main feature of the BGE/UPBGE and its greatest strength is the total integration with Blender, no other engine has this).

I will release an additional version (0.2.5) that will be like 0.2.4 but without the commits that made it unstable. After that, I will replace the master branch with the 0.3 branch which is what we are working on now.

What is being done in that branch is to move all commits from the 0.1.9 upbge version to those of 0.2.5. Once this has been done we can see what improvements or how we can mitigate the features we have lost with the change of libraries.

I close the thread.
