### ISSUE TITLE
upbge 0.3.0 - sound actuator not working in standalone mode

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#1074]
sound actuator is not working in standalone*

steps to reproduce

make a sound (music etc) actuator - play it in embedded,

try standalone. (no audio)

**Comment by BluePrintRandom** [comment]
[audio_test.zip](https://github.com/UPBGE/blender/files/3839687/audio_test.zip)
https://www.youtube.com/watch?v=hpS4k4VJQp0&feature=youtu.be

**Comment by youle31** [comment]
Idk exactly where the issue comes from but I manage to have sound in blenderplayer doing:

![Capture](https://user-images.githubusercontent.com/10052509/68987031-c4fdc900-0825-11ea-8a48-79a6e886f03c.PNG)
 in gpg_ghost.cpp

AND as last SDL lib has issue in 2.8, I copy the SDL2.dll from 2.79b in my eevee_bge folder.

but idk what's wrong with openAL as it is working in the viewport...

Audio was working previously in blenderplayer.Maybe this is the changes I did when I worked on bpy in blenderplayer which breaked audio...

**Comment by youle31** [comment]
in sound.c, the device changes from OpenAL to SDL, and as SDL doesn't work properly with the current 2.8 lib (on my computer at least), the sound is not played.

The issue happens here:

![Capture](https://user-images.githubusercontent.com/10052509/68987543-2f653800-082b-11ea-84b8-e184adcb0b63.PNG)
![Capture](https://user-images.githubusercontent.com/10052509/68987646-a39fdb80-082b-11ea-89db-2b3dd18dc21a.jpg)

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/blender/commit/1b2a8854d2eeec0df4056a77ba5c30b9e1ca6063

**Comment by BluePrintRandom** [comment]
I confirm it's fixed :D
