### ISSUE TITLE
UPBGE-2.79 vs UPBGE-2.8

### ISSUE THREAD

**Issue by Frankjore** [UPBGE/blender#1080]
It would be very well received, a compatibility between UPBGE-2.79 and UPBGE-2.8 projects, texture allocation, bone animations ... etc. A non-Blender format (3ds, obj ....) is better accepted than a Blend file

**Comment by youle31** [comment]
We can't have a total backward compatibility due to massive changes in viewport. We can't have backward compatibility for blender internal materials, it has to be recreated using eevee's nodes. For animations, some things have changed too, but it is not documented for now.
Else some things can't be like before (overlay scenes, background scenes can't really be handled due to integration with depsgraph...).

For now, and for a long time, it will be an experimental project. To be honest, I think the design to plug BGE on 2.8 is not good, even if we can do many new things because we can use bpy API in realtime.

Personally, I don't think this project can become really reliable as a tool to create "more than 1 week projects". For me, this is just cool to play with blender, create small games or interactive creations, discover bpy, discover what was not possible in bge (like using the viewport fonts, using modifiers, particles...).

upbge0.3 is not my branch, it is lordloki initiative. I think we'll code just for fun, and we'll see later if we can provide something ~stable, but it might take a long time.

About backward compatibility, I saw that lordloki recently restored versioning_upbge file. Then it can improve a bit backward compatibility in some specific areas. But a full backward compatibility is impossible. Some things which were done with bge module have to be done with bpy now. Materials are not the same, mesh system is not the same (you need to use bpy to deform meshes), layer system has been replaced with collections.

I'd say that the current design already offers almost the maximum backward compatibility possible for some script, and small blend files. But to port a big project from 2.7 to 2.8 it would require a very big work.

**Comment by Frankjore** [comment]
Would it be possible to make an APP that converted the projects 2.7 and 2.8?

**Comment by lordloki** [comment]
It is not possible. Sorry
