### ISSUE TITLE
Text always on top of objects with alpha blend/sort

### ISSUE THREAD

**Issue by elmeunick9** [UPBGE/blender#119]
Text objects always appear on top of objects that have alpha blend enabled. Using alpha clip is not a good enough alternative.

Example .blend:
http://s000.tinyupload.com/index.php?file_id=76131152442303363793

![im](https://cloud.githubusercontent.com/assets/4674207/15607958/eeedb24e-2416-11e6-8398-29f4ec6b2cd1.png)

**Comment by youle31** [comment]
Hi! This is a know issue: I paste the 2 related bug reports:
- https://developer.blender.org/T35606
- https://developer.blender.org/T29804 (see particularly dfelinto comments)

In upbge I remarked that only 2 alpha blend modes were working (alpha clip and alpha anti aliasing)

I quickly tested GPU_set_material_alpha_blend options in DisableForText() but without success for the moment.

We have to take care about performances if we want to fix that because some alpha blend mode seems to slow down the bge and this makes debugging performances issues harder (we use render 2D text and DisableForText() also for debugging messages.)

Thanks for report!

**Comment by panzergame** [comment]
Currently text are rendered in KX_FontObject::DrawFontText called by KX_Scene::RenderFonts.

Which means that for the moment the text are not sorted by depth (contrary to meshes objects) between they and also with the others objects. Indeed it's a wrong way here.

Then the supposed function IndexPrimitives_3DText for text is not called, it should be the case, but here the text parsing form DrawFontText should be moved in IndexPrimitives.

**Comment by panzergame** [comment]
first plan:
For texts objects:
`
RAS_MaterialBucket:
    --> RAS_DisplayArrayBucket []:
        --> m_displayArray = NULL
        --> RAS_MeshSlot []:
            --> RAS_TextUser(RAS_MeshUser): // Hineritance from RAS_MeshUser but for text objects.
                --> m_texts[] // the texts lignes.
                --> m_fontId // the BFL text number.
                --> m_size
                --> m_dpi
                --> m_aspect


For the render:
    
RAS_BucketMaterial::RenderMeshSlot:
    if material->GetDrawingMode() & RAS_RENDER_3DPOLYGON_TEXT:
        --> RenderText3D(GetFontId(), GetTexts(), GetSize(), GetDpi(),  GetColor(), GetMatrix(), GetAspect()) // getter from RAS_TextUser and RAS_MeshUser
`

**Comment by panzergame** [comment]
Fixed in 7038db28fa6715915235df06a075d1a8f5282dd8.
