### ISSUE TITLE
Joystick(button) delay

### ISSUE THREAD

**Issue by RockyMadio** [UPBGE/blender#128]
Hi,

i would like to report a problem with the joystick sensor. I found out that  if  i just use 1 single scene, it doesnt give any negative effect, but when i try to include an overlay or underlay scene, the button inputs become very unresponsive.
Î am glad if you could tell me any solution.

Blender 2.77

Thank you

**Comment by youle31** [comment]
Hi! If the bug is in blender 2.77 official, could you report it here: https://developer.blender.org/maniphest/project/30/ ?

It makes the stuff easier for us to know if the bug is only upbge related or not?

Could you also join example file please? Thanks!

As lordloki is refactoring joystick management in upbge, I mark this issue as low priority for the moment. We'll see if the bug is still there after refactor.

**Comment by panzergame** [comment]
Fixed in 1205b6a372a5838218899142d7df5e452d6606e5
