### ISSUE TITLE
Performance decrease on desert level and other files

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#149]
In 0.0.8 I had 125fps at ge start in desert level:

- 1 performance decrease here: https://github.com/UPBGE/blender/commit/a88463103c4174ed2e6e2c900bfbfba0c4fccbf8 (merge commit with Benpoit Bolsee modifs (120 fps instead of 125. I think it is caused by the modifs in SetViewMatrix)

- 1 performance decrease here: https://github.com/UPBGE/blender/commit/45493efdee5a5242d41dac0ed1c51ef2299aa6f9 (88 fps instead of 125)... We have to investigate on isShadowDone or ask Benoit Bolsee. (Confirmed by reverting the commit->I have 120 fps again)

**Comment by panzergame** [comment]
For isShadowDone as explained in the commit message, this behaviour is false and dangerous. But fortunately the user can simulate this by setting the lamp using static shadow after the first video render, e.g
```
lamp.staticShadow = False
tex1.refresh()
lamp.staticShadow = True
tex3.refresh()

### render ####
```
In this case the user will know that none object should move between each renders. @youle31 : As this workaround is not very intuitive, do you think we should add it in a kind of user doc/FAQ ?

**Comment by youle31** [comment]
isShadowDone was set to false each frame in KX_KetsjiEngine.cpp so no chance that the shadow buffer is not rendered. tex.refresh(bool) method cannot modify the shadow buffer.

 ImageRender::Render is called after normal scene render. So If you just comment m_engine->RenderShadowBuffers(m_scene); in ImageRender::Render() in a normal usage of render to texture, the shadows will be there: http://www.pasteall.org/blend/42657 . 

Before Benoit Bolsee commit THERE WAS NO CALL to RenderShadowBuffers in ImageRender.

I don't know in what specific case isShadowDone could be false when you use render to texture. Maybe it's needed for bge.texture.ImageRender.source.render() new method that puts an image into a fbo but doesn't refresh the texture? I don't know. It seems weird to me. But it is surely needed by newly added features.

One thing that is sure is that you don't need to call RenderShadowBuffers in ImageRender::Render each time you call it. If you do so, the performances drastically decrease.

So we have to find in what case the shadow buffer is not rendered and we need to call it in ImageRender::Render()

**Comment by panzergame** [comment]
@youle31 : `ImagerRender::Render` is called from python `refresh` and `render` functions and these functions are called in the logic step which is before the render (excepted `scene.post_draw`).
Anyway the user can move object just before a image render and undo these object just after, in this case the shadows will be wrong. I'm not against render shadow in image render because it can be useful also the user as i said can easily disable shadows or set the lamp invisible so the performance problem is limited if the user is well documented.

**Comment by youle31** [comment]
You're right, so there is one frame gap beetween scene render and image render. I made a patch for this. I'll try to fix this. But nevertheless we can't render shadow buffer each time we call ImageRender::Render. This has a too big performance impact and I don't know in what case it is usefull because when you comment this line you have the shadows.

**Comment by youle31** [comment]
http://www.pasteall.org/71775/diff Something like that. But I don't understand all. This only fix gap beetween actuator movement and ImageRender

**Comment by youle31** [comment]
I propose to simply remove RenderShadowBuffers till we don't know the usefulness of this.
Do you have an example file where the shadow is wrong when you don't use RenderShadowBuffers in ImageRender::Render()?

**Comment by panzergame** [comment]
As the shadows are updated in the final render. If on object in the scene move, then the shadow will be invalid because is it not yet recomputed, but this same is shadow will be used for any image render which are before the final render which recompute the shadow. By recomputing the shadows in image render we make sure that a moved object as updated shadow.

Example file: http://www.pasteall.org/blend/42660

**Comment by youle31** [comment]
@panzergame: http://www.pasteall.org/blend/42661

**Comment by youle31** [comment]
solved in https://github.com/UPBGE/blender/commit/ba0fe4f3d2dd89eac36625e3fc9b93f94f9c2614
