### ISSUE TITLE
Request: Glow effect

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#18]
Add support for build-in glow effect. The idea is to use a single object(mesh) to only glow. This feature is useful, when the game developer wants specific object to glow instead of the entire screen. For example: the monitor, body cloth parts, gold and etc...
useful links -> http://www.learnopengl.com/#!Advanced-Lighting/Bloom
http://www.humus.name/index.php?page=3D&ID=32
http://http.developer.nvidia.com/GPUGems/gpugems_ch21.html

**Comment by DCubix** [comment]
We need to implement FrameBuffer Objects before implementing this.

**Comment by Akira1San** [comment]
Yeah fbo is important for the 2d filters.

**Comment by adriansnetlis** [comment]
Note that this is a thing based on HDR(see my request).
This is selective blur actually. So you take the rendered texture, subtract bias value from it and than add the resulting color to the rendered texture. This will result in correct HDR-based bloom.
However, you can already kind of fake this in filters. But it still isn't the real thing, because we don't have 16-bit float depth.

**Comment by Akira1San** [comment]
Ok, then lets have HDR for 0.8!

**Comment by Akira1San** [comment]
Since 0.1.2 is out and we have fbos. I would like to see this feature. a buildin glow shader would be faster, than a custom shader or a filter. Nice link: http://docs.cryengine.com/display/SDKDOC2/Glow+Effect
