### ISSUE TITLE
Request: volume raycasting

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#20]
Could you impliment volume ray casting in the bge.Here is the link.
http://blenderartists.org/forum/showthread.php?227384-Volume-Ray-Casting-in-BGE-(blend-included)
With ten thousand cubes the framerate did not drop.

**Comment by DCubix** [comment]
It's an interesting feature, but I don't see where could we use this...

**Comment by lostscience** [comment]
You can cut meat in the bge with it.

**Comment by lostscience** [comment]
Did you look up the definition of volume ray casting on Wikipedia?

**Comment by sdfgeoff** [comment]
While I do not know the value of implementing it as martinsh has done in that post, I would be intested in being able to do very basic voumes in BGE ie: a polygonal model, but instead of rendering the polygons it treats the interior as a voume with customizable density. Much like using blender internal volume renderer without passing in volume data.
It would be useful for water, mist, smoke etc.
