### ISSUE TITLE
Re-instance physics mesh on a object with replace mesh does not target the correct mesh

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#211]
https://youtu.be/_9rX3Mhp1Vk

I am using libNew to generate terrain, but then I need to re-instance the physics meshes of the planes 
and it does not work. 

is there anyway to replace a physics mesh?

I thought replaceMesh(LibNewMesh,1,1) should do this right?

**Comment by elmeunick9** [comment]
I had this problem before. It's not that the Physics mesh doesn't get replaced, but that it's shared across all instances of the same object. In short to replace the physics mesh of multiple objects you must make sure they really are diferent objects, not instances.

Though there is a workarround for this, I also think that this should be fixed on the python API, somthing like an option on LibNew that creates an entarly new object with all data copied (instead of sharing data wich is what it does now).

The workarround, implemented on BGECore with the ObjectGenerator class [](http://bgecore.royalwebhosting.net/dynamic.html#copying-objects), is creating a sparate blend file with your generic mesh (say a 100x100 grid) and then load it multiple times with libLoad. But not so easy, BGE tries to make sure you don't load the same blend multiple times, this can be bypassed too by loading manually the file and then using the data mode of libload (making sure you assign new ids each time).

`with open(path, "rb") as input: data = input.read()`
`bge.logic.LibLoad(path+str(id), "Scene", data, load_actions = False, load_scripts = False)`

I use the scene mode to make sure we load the object, not the mesh. Make sure your file only contains your generic object and nothing else.

As a side note, the only reason for wanting this that I can think of would be editing meshes on realtime, it would be nice to have blender tools inside the BGE API to do that, instead of reinventing the wheel.

**Comment by BluePrintRandom** [comment]
how do I use the loaded object?

Normally I do

added = own.scene.addObject()
libNew
ReplaceMesh

could you modify the code you provided so I can access it as it loads?(for
my terrain generator to store and reference it after all tiles are in?

with open(path, "rb") as input: data = input.read()
bge.logic.LibLoad(path+str(id), "Scene", data, load_actions = False,
load_scripts = False)

**Comment by panzergame** [comment]
@BluePrintRandom: since UPBGE 0.0.6 (http://doc.upbge.fr/releases.php?id=0.0.6), there's a new argument for the function reinstancePhysicsMesh to duplicate the physics mesh. But this argument is not exposed in replaceMesh. for your case, you have to do:
```
obj.replaceMesh(newmesh, True, False)
obj.reinstancePhysicsMesh(None, newmesh, True)
```

**Comment by BluePrintRandom** [comment]
Thank you this works fine panzergame!

**Comment by elmeunick9** [comment]
Ahh it was fixed already, my bad.

@panzergame 
On the documentation there's a warning, it recomends using `replacePhysicsShape(gameObject)`. I understand that the dupli argument duplicates the mesh, does it mean that we'll have more than one mesh on KX_GameObject.meshes?

**Comment by panzergame** [comment]
`
@panzergame
On the documentation there's a warning, it recomends using replacePhysicsShape(gameObject). I understand that the dupli argument duplicates the mesh, does it mean that we'll have more than one mesh on KX_GameObject.meshes?
`
The dupli argument will only make the physics mesh/shape unique. Which cost memory than share it between objects like the default behaviour.
