### ISSUE TITLE
Re-calculate normals using threading?

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#212]
after I generate a Terrain mesh, I need to recalculate it's normals

this can be slow using iteration in python,

is object.meshes[0].recalculateNormals a good idea for a C or C++ command?
(for raw speed?)

(it would be a feature of KX_Game_Object.meshProxy? )

**Comment by panzergame** [comment]
Recalculating normal is more vague than we can think, because of the flat surfaces. Will the user want to smooth everything or flat some surfaces ?
A patch was already proposed a long time ago and refused for these issues.

`(it would be a feature of KX_Game_Object.meshProxy? )`
sure.

**Comment by DCubix** [comment]
A thread wouldn't mean it's fast. It means it does a job without blocking the main thread.

**Comment by youle31** [comment]
I personnaly think that it's too complex (I had a look at the Blender code and it's very long and complex) and the usage will be too restricted (very few people would use that) to justify to make a patch for that.

I think it's better to use bpy in a .blend to create your terrain with all modifiers you want, recalculate normals with bpy API then load it in in your game.

**Comment by BluePrintRandom** [comment]
what if you modify the terrain in real time? (crater etc?)



I think soft bodies have code somewhere to recalculate normals each frame?

**Comment by youle31** [comment]
In fact Soft bodies use the same method as KX_VertexProxy::setNormal method but I don't know understand how this works (Is this working at least?)... Why mathutils.geometry.normals() doesn't work at runtime?

I personnaly don't want to make this patch, but maybe someone in the team would like to do it. @panzergame and @DCubix : Some of you guys want to make this feature?

**Comment by BluePrintRandom** [comment]
mathutils.geometry.normals() works with heavy itteration, and is not great
for runtime because you have to loop through the whole mesh several times.

however having a method that recalculates normals automatically
for only vertex that change would be nice, or that looped through all
vertex using threadsbor something faster then 1 single gil thread.

On Sep 9, 2016 5:57 AM, "youle31" <notifications@github.com> wrote:
>
> In fact Soft bodies use the same method as KX_VertexProxy::setNormal
method but I don't know understand how this works (Is this working at
least?)... Why mathutils.geometry.normals() doesn't work at runtime?
>
> I personnaly don't want to make this patch, but maybe someone in the team
would like to do it. @panzergame and @DCubix : Some of you guys want to
make this feature?

**Comment by Jay-Parker** [comment]
It's been a while since I've done anything Blender related, but I thought I'd chime in on this since I tried the recalculate normals patch.

Right, recalculating normals is quite easy, and there are number of different ways to do - some of which are good for real time. It's important to note that each method will produce varying results. Now, when you get meshes with multiple materials and strange mixes of smooth and solid faces it becomes a lot harder. I managed to get something that worked for most cases, but with more complex/unusual material/smooth/solid combinations it would produce odd results. My own view was that it comes down to poor mesh design rather than a coding problem, but the review of the patch required something that would work across all cases. 

Additionally, if I remember correctly, it was requested that the patch produce normals that blender it's self would produce. The problem here is that blender as access to a lot more mesh data (face angles, sizes, edges etc.) that it uses, that you don't have in the BGE. This means that blender can produce reasonable results with even the worst of meshes. Normal calculations designed for real-time applications make a lot of approximations, and don't come close to how blender calculates the normals.

The closer I came to handling bizarre meshes and replicating blender's normal calculations the more iterations over the meshes/materials I needed to do and the slower it became. Pretty much to the point where my initial python solution (which used a method appropriate to my needs) was nearly as efficient.

Like you I wanted to speed up normal calculations are part of a procedural terrain generator. While I was able to create something that worked for my needs, the result was not as good as python in the end. Because my terrain was made up of various planes, my python normal recalculation used data from the procedural generator to determine normals. So when recalculating one plane it always knew what the plane next to it looked like and include that in them. When doing in it C++ I didn't have that data, the functions only knew about the one mesh they were operating on. So between my terrain segments there were visible lighting seams caused by the normals not including neighbouring planes in their calculations. 

I could return to my patch for recalculating normals, but it wouldn't replicate blender's implementation or effectively manage silly meshes. My personal choice would be strip what I wrote back to a simpler real-time approximation rather than replicate blender's approach and place the responsibility of sensible meshes on the artist. If there's enough demand and people are happy with this I'll do it.

Sorry for the long post!

**Comment by BluePrintRandom** [comment]
I had a similar issue with my generated normals (each face was calculated
seperate from neighbors)

I ended up using a KD tree to find all points that shared a XYZ cord, and
then averaged them

this is how that ended up looking
https://www.youtube.com/watch?v=pmEPn9xe_-0

**Comment by lostscience** [comment]
Jay-parker you could have addon in blender make the mesh you choose into something that is perfect for your algorithm.

**Comment by BluePrintRandom** [comment]
I think that animated objects and soft bodies recalculate their normals after each deformation,

maybe this code exists already?

**Comment by BluePrintRandom** [comment]
please re-open?

I have a example here, and if we have too much deep iteration in py here for bigger meshes.

we need a compiled code to recalculate normals smooth, and flat  and hybrid 
(hybrid would be slower of course and could even be supported later)


I can provide python code that does what I need it's just plain too slow.


`import bge
import mathutils
from mathutils import Vector
import math

def X_round(x, prec=2, base=1/8):
  return round(base * round(float(x)/base),prec)

def main():

    cont = bge.logic.getCurrentController()
    own = cont.owner
    
    if 'Kd' not in own:
        size = own.meshes[0].getVertexArrayLength(0)
        tree =  mathutils.kdtree.KDTree(size)
        master = {}
        for v in range(size):
            vert = own.meshes[0].getVertex(0,v)
            
            tree.insert(vert.XYZ,v)
            master.update({ (v):vert })
            
            
        tree.balance()
        own['Kd']=tree
        own['Master']=master  
   
    elif own['Mountain']<=99:
        own['Mountain']+=1
        r =2
        near  = own['Kd'].find_range(Vector([0,0,0]), r)     
        
        for v in near:
            vert = own['Master'][v[1]]
            
            if v[2]>1.75:
                vert.color = [.1,.1,.1,1]
            grab = vert.XYZ
            grab.z += (.25-(math.pow(v[2],3)))*.00125
            grab.z += .01
            
            
            vert.XYZ = grab
    
    #Recalculate Normals
    posList = {}    
    if 'FaceDict' not in own:
        faceDict = {}    
        for face in range(own.meshes[0].numPolygons):
            poly = own.meshes[0].getPolygon(face)
            v1 = own.meshes[0].getVertex(0,poly.v1)
            v2 = own.meshes[0].getVertex(0,poly.v2)
            v3 = own.meshes[0].getVertex(0,poly.v3)
            v4 = own.meshes[0].getVertex(0,poly.v4)
        
            faceDict.update({(face):[v1,v2,v3,v3]})
        
        own['FaceDict']=faceDict
        print('Generated face dictionary')
        
    for face in own['FaceDict']:
        verts = own['FaceDict'][face]
        
        value = (verts[0].normal + verts[1].normal + verts[2].normal+verts[3].normal)/4    
        
        
        
        verts[0].normal = value
        verts[1].normal = value
        verts[2].normal = value
        verts[3].normal = value
        
        
        vect = (X_round(verts[0].XYZ.x),X_round(verts[0].XYZ.y) ,X_round(verts[0].XYZ.z) )
        if vect not in posList:
            posList.update({vect:[verts[0]]})
        else:
            posList[vect].append(verts[0])
        
        
            
        vect = (X_round(verts[1].XYZ.x),X_round(verts[1].XYZ.y) ,X_round(verts[1].XYZ.z) )
        if vect not in posList:
            posList.update({vect:[verts[1]]})
        else:
            posList[vect].append(verts[1])
            
        
        
            
        vect = (X_round(verts[2].XYZ.x),X_round(verts[2].XYZ.y) ,X_round(verts[2].XYZ.z) )
        if vect not in posList:
            posList.update({vect:[verts[2]]})
        else:
            posList[vect].append(verts[2])
        
        
        
        vect = (X_round(verts[3].XYZ.x),X_round(verts[3].XYZ.y) ,X_round(verts[3].XYZ.z) )
        if vect not in posList:
            posList.update({vect:[verts[3]]})
        else:
            posList[vect].append(verts[3])
                        
            
             
    for position in posList:
        position = posList[position]
       
        N = 0   
        for vert in position:
            if N==0:
                N=vert.normal
            else:
                N = (N+vert.normal)/2
        for vert in position:
            vert.normal = N       
                        
                
            
            
                
            
    
                        
                
            
        
main()
`

**Comment by BluePrintRandom** [comment]
`PyObject *KX_MeshProxy::PyRecalculateNormals(PyObject *args, PyObject *kwds)
{
	int Mode;
/*I gutted a bunch of stuff here and proabbly missed something*/
	

	if (!PyArg_ParseTuple(args, Mode) ||
		!PyMatTo(pymat, transform))
	{
		return NULL;
	}

	

	/* calculat normals for mesh verts */
	unsigned int mit_index = 0;
	for (list<RAS_MeshMaterial>::iterator mit = m_meshobj->GetFirstMaterial();
		(mit != m_meshobj->GetLastMaterial());
		++mit, ++mit_index)
	{
		

		RAS_MeshSlot *slot = mit->m_baseslot;
		RAS_MeshSlot::iterator it;
		ok = true;

		for (slot->begin(it); !slot->end(it); slot->next(it)) {
			size_t i;

			for (i = it.startvertex; i < it.endvertex; i++) {
				RAS_TexVert *vert = &it.vertex[i];
				if (uvindex_from != -1) {
					if (uvindex_from == 0) vert->SetNormal(1, vert->GetNormal(0));
					else                   vert->SetNormal(0, vert->GetNormal(1));
				}

				/*this is where I need to setup the modes and calculate normals*/
				switch (uvindex) {
				case 0:
					vert->TransformUV(0, transform);
					break;
				case 1:
					vert->TransformUV(1, transform);
					break;
				case -1:
					vert->TransformUV(0, transform);
					vert->TransformUV(1, transform);
					break;
				}
			}
		}

		/* if we set a material index, quit when done */
		if (matindex == mit_index) {
			break;
		}
	`}
``

this is where I am so far 
(gutted transform UV and started hacking it into recalculate normals)
