### ISSUE TITLE
Other: Just let me know if you need me to test a win64 build of a new commit 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#22]
send me a email and I will pull down a clone and build it, and test it out :+1: 

Blueprintrandom1@gmail.com
I am on a Alienware alpha (lowest spec) 

"4th Generation Intel® Core™ i3 processor

Windows 8.1 Home

4GB Memory

500GB Hard Drive"

Was built as a entry level for current gaming computers.
if I can get 60 fps..... the modern market should.

**Comment by youle31** [comment]
@BluePrintRandom : Hi, as the movement sensor has been merged to the upbge with threshold option, if you want, you can test it. I think the parallax patch will also be merged soon (I have to make other video tutorials on how to use it), then you could test it too.

As a libraries update has been made recently, you have to rebuild upbge from scratch (else cmake step is not needed).

steps:

- You can remove your upbgeBuild folder and create a new empty one.
- run your upbgeUpadate.bat script to update upbge sources
- run cmake and select the compiler (Visual studio 12 2013 64) sources folder and build folder. 
Click on generate one time to have build options in red, then a second time to have build options in white. Then click generate.
- Go in your upbgeBuild folder and open blender.sln
- Select Release instead of debug and wait for visual studio to be ready.
- Right click on INSTALL, then Build.
- Go into upbgeBuild/bin/release and open blender.exe

We set the default threshold value to 0.01 because below this threshold a movement can be detected for rigid bodies at the start of the game engine even if they seems to not move.

You can set threshold and axis with sensor.threshold = (float) and sensor.axis = (int beetween 0 and 6).

You can also access the sensor status (print(sensor.status)-->1 = just activated, 2 = active, 3 = just released)

**Comment by BluePrintRandom** [comment]
Building now :+1:

**Comment by panzergame** [comment]
i close this issue since is not really a one.
