### ISSUE TITLE
Request: More build-in 2d filters

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#23]
Add support for more build-in 2d filters or the most used ones!
Today game engines have already build-in filters like: Bloom, Chrome, AO, Color correction, Fxaa, etc... An example would be the link -> https://github.com/mikepan/BlenderGEResourceKit An already build library from mikepan.

**Comment by youle31** [comment]
Hi, I think adding these filters as Builtins filters is a bad idea because you can't tweak/modify the code as you want. What I thought about this was adding a new GLSL 2D filters templates menu where you can find all this filters, executed as custom 2D filters, so you can access the code, modify it (for example, increase or decrease numSamples in a bloom filter, change colors in a color filter...)

Thanks for the link to mikepan library. I think we'll add many many filters from Martinsh, Mike Pan or other well know GLSL blender masters in the upbge :)

**Comment by Akira1San** [comment]
Cool. I like the idea. :)

**Comment by panzergame** [comment]
This is better done by an addons than a thousand of internal templates.
