### ISSUE TITLE
Here's the file

### ISSUE THREAD

**Issue by Yetta1** [UPBGE/blender#232]
BPPLAYER crashes when set to fullscreen or Desktop mode.
build: UPBGE 0.1.0 hash: b6060d3 date: 2016-09-26
[MasterUPBGE_basic.zip](https://github.com/UPBGE/blender/files/496748/MasterUPBGE_basic.zip)

**Comment by Yetta1** [comment]
Dynamic character nodes.
File crashes UpBGE on open.
Opens on vanilla Blender but crashes when turning on materials.

[MasterUPBGE_dynamic.zip](https://github.com/UPBGE/blender/files/497846/MasterUPBGE_dynamic.zip)

**Comment by youle31** [comment]
@Yetta1 : I forgot to tell you yesterday that it could be usefull to give us your system informations in the bug report (OS, GPU). In the case you're on windows could you test your files with this built and tell us is this is ok? https://drive.google.com/file/d/0B3GouQIyoCmrdjRmTEpGcC00THc/view?usp=sharing

In the case you're on Linux, the builbot will build my branch ge_texcrash tonight normally. You could find it in https://download.upbge.fr/download/buildbot/branch/

If the bug is solved you can close the issue. Thanks for bug report

**Comment by youle31** [comment]
@panzergame: Yetta1 told me that it fixed his issue.

**Comment by youle31** [comment]
https://developer.blender.org/T49484

**Comment by youle31** [comment]
Fixed in BF Blender
