### ISSUE TITLE
Some issues with main website

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#236]
Just a couple of thoughts about the main website and how it could be improved:

1. The download button does not take you to the one you should download. It is confusing for users to try figure out where the build they want it. There should be a "download latest stable [window, max, linux]" link on the download page.
2. UPBGE linux build has requirements (other than stock blender?) such as LLVM and pugixml These should be listed somewhere.
3. The letter 'U' under resources is really low resolution. It may be intentional, but it looks bad. If you want someone to make some logo's/symbols, I'm perfectly happy to.

**Comment by Momel15** [comment]
Addition: 

It would be nice if you could change the behavior of the menu buttons on the documentation page.
As you can see on the picture, you can only click on the text, not on the button itself because the link is only on the text.
![Documentation Page Menu](https://cloud.githubusercontent.com/assets/17685000/19013547/3125a61e-87d4-11e6-99ff-17db898119c5.jpg)

**Comment by Thibo7x** [comment]
Hello,
Thanks for your comments, it is very useful

sdfgeoff, I worked on an other download website ; I hope it will be in place in some hours. I added informations about pugixml and llvm.
For the main website itself, I will modify the U ; you are right, it looks bad...

Momel15, I will correct it in the future days. Thank you for reporting this

**Comment by panzergame** [comment]
@sdfgeoff, @Momel15 : Is everything fine now ?

**Comment by sdfgeoff** [comment]
Everything looks good from here.
