### ISSUE TITLE
Bug with GLSL shader (I think) (Sky)

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#279]
http://pasteall.org/blend/index.php?id=44124 (Works in BF bge, not in upbge)

**Comment by panzergame** [comment]
Can you bisect the faulty commit ?

**Comment by youle31** [comment]
Same first bad commit as for ground shader: https://github.com/UPBGE/blender/commit/0f527cebe45d76cb49228b6312e1aeaf3d912285

**Comment by panzergame** [comment]
Previously in BFBGE is appears that the light source position set was not in view space and then used as it in the shader. But this was a bug caused by the render of shadows just before. UPBGE solved this issue but the files using this issue are so broken.

To fix the issue replace the usage of:
`gl_LightSource[0].position`
by
`gl_ModelViewMatrixInverse * gl_LightSource[0].position`
to have a world space light position.

**Comment by youle31** [comment]
Thanks for explaination 👍
