### ISSUE TITLE
Object with alpha = 1 sometimes get transparent or semi-transparent

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#285]
Hello to all.

In my file <(it's too large for GitHub) http://dropmefiles.com/r6syz > there is a bug with object Cube_test.
I has turned on z-transparency in material tab, it's alpha value = 1; sometimes it becomes transparent or semi-transparent when the sky object is on the background.

Screenshots:
![2016-11-04 21-56-59](https://cloud.githubusercontent.com/assets/12682937/20020706/5091c9c0-a2db-11e6-82fc-e15eaaa4e988.png)
![2016-11-04 21-57-07](https://cloud.githubusercontent.com/assets/12682937/20020705/50918e1a-a2db-11e6-9ef8-1e47d79f4d3b.png)
![2016-11-04 21-57-13](https://cloud.githubusercontent.com/assets/12682937/20020707/5095504a-a2db-11e6-94ef-3b9607d552b1.png)
![2016-11-04 21-57-16](https://cloud.githubusercontent.com/assets/12682937/20020708/50976498-a2db-11e6-84f6-006299de99b4.png)

System: Debian x64 unstable
UPBGE: 0.1.0 (01.10.2016, 12:08)

FIle is on the side website, it'll be deleted after week. When you'll need it again - write here please, I'll upload it again.

Best regards,
Vladislav

**Comment by panzergame** [comment]
This bug is caused by the object sort of transparency meshes. Currently the sort takes in account only the center, and in this case the sky center is closer than the cube center, which caused the sky to be rendered last.

To solve this issue we can add to the center distance the radius of the object AABB, but for this we have to wait ge_bound.
