### ISSUE TITLE
Ability to choose object in property sensor and actuator

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#292]
Hello dear friends.

I wanted to write this long time ago, but I had not time yet.
I think it would be great to add to "property sensor" and "property actuator" **ability to choose object**, on which sensor\actuator will look\edit properties. 
If object was not specified - sensor and actuator will work with properties on owner object (object, on which logic brick is).

Also I suggest to **change places** of "Evaluation type" and "Property" lines for sensor; "Mode" and "Property" lines for actuator. 
That would be more logical, just like expression: property (evaluation type) value; or first value (what to do) second value.
Also it would be good to **rename** "Evaluation type" line in "Property sensor" to "Mode" to be it more similar to "Property actuator" (where it's already called "Mode"). It's more short and clear.

Approximate look of "property sensor":
![property_sensor](https://cloud.githubusercontent.com/assets/12682937/20106410/b7556f90-a5dd-11e6-9bc7-85356406cb26.png) 

Approximate look of "property actuator":
![property_actuator](https://cloud.githubusercontent.com/assets/12682937/20106422/c33a5096-a5dd-11e6-9f47-dcab2d078e9a.png) 

**Why is it needed?**
This is needed to simplify creation of game logic using logic bricks.
There will be no need extra logic bricks like "message actuator\sensor", it's controllers and actuators for every case.
Example of little trade system without adding ability to choose object:
![document_003](https://cloud.githubusercontent.com/assets/12682937/20112039/5796e000-a5f3-11e6-9864-179e0f065595.png)
_(full size image: https://pp.vk.me/c638518/v638518447/998e/YFCOLqQ3jmg.jpg)_
Example of little trade system with adding ability to choose object:
![document_002](https://cloud.githubusercontent.com/assets/12682937/20112046/61068eec-a5f3-11e6-995f-1c6a257cd78a.png)
_(full size image: https://pp.vk.me/c638518/v638518447/9984/qjh_JeOEms4.jpg)_

We can see, that when logic is present on one object, when there is lesser amount of logic bricks and their nets - that clearer is logic.

Also such behavior will be useful for many different cases, this is not only the decision for specific task.

**Advantages:**
-logic system becomes more easy clear to read and write
**Disdvantages:**
-needs extra work from game engine developers

Please, tell me what you think about this.

Best regards,
Vladislav

**Comment by youle31** [comment]
Hi, as I said to BPR, I think we shouldn't work on logic bricks until we know what will be the "plan" to refactor logic for 2.8. Except if there is a bug to solve.

The reason is that upbge will surely be aligned with 2.8 logic system. As it will need some work to code again what is already specific to upbge logic, I think we should wait to have a better idea on what will happen (or not) in BF bge to continue to work on logic.

I let the feature request opened to have other devs opinion on the subject.

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.

**Comment by youle31** [comment]
@vlad1777d : Sorry for my overreaction yesterday... I worked in an office, I had more and more stuff accumulating over my desktop, until I burned out. A big burn out. This explain why now I'm retired at 33 years old. I'm a very stressed person. The issues section was oversaturated by feature requests whereas it is intended to be a section to only report bugs. I wanted to do some clean up so we can focus on bugs (because they are prior to requests). So the purpose was first to reorganize this section. The second was to alleviate pressure on my shoulders because I'm contributing to upbge like I do with a job, when too many stuff is accumulated "over my desktop", this is really stressing me.

But I shouldn't have overreacted like that. It happens often unfortunately because of my stress.
