### ISSUE TITLE
 environment lighting -> sky color bug

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#294]
In world ->  Environment lighting -> sky color is not working in standalone, but works in embedded. tested with Upbge 011 and bfbge, the result looks the same to me.

**Comment by youle31** [comment]
Hi! I begun to implement it here: https://github.com/UPBGE/blender/pull/258 but I closed the pull request for now because maybe Alexander Romanov will do it for Blender (not now but...). Blender4Web (A. Romanov and friends) team worked on environment lighting in the viewport. So I trust him more than me for this stuff and I wanted to clean up a bit feature request list to alleviate pressure on reviewers. The branch can still be tested.
