### ISSUE TITLE
standalone and blenderplayer.exe resolution and fullscreen option ignoring user setting

### ISSUE THREAD

**Issue by hugobarreira** [UPBGE/blender#304]
In KX_KetsjiEngine.cpp when using full screen option the resolution seems to be set from blender software windows as a reference instead of user setting in standalone player resolution.
This results in a full screen window with bands around if the user sets the resolution to be smaller that the system resolution.
The desired result is to have the resolution set by the user to scale to the full screen area of the screen without the bands if the resolution is scaled proportionally, note that the framing option should also scale appropriately .

**Comment by panzergame** [comment]
The render area have to be the same, and after we will scale it two the screen, but it introduce some issues. The most important is about mouse coordinates, the mouse will follow the screen resolution instead of the render resolution if you want to pick up a color from the screen.

For the moment i don't really know…

**Comment by BluePrintRandom** [comment]
can we scale the mouse cords in standalone by the screen width?

etc?
