### ISSUE TITLE
PythonComponent file paths

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#307]
Currenly the PythonComponent looks for scripts in the current directory and in the current blend.
A common thing to do is to use a script folder, and to do this by linking a scene from a blend in the script folder, as this expands the search path.

It would be great if the PythonComponent would also look in the folders of linked in blends. Or at least have some way of expanding it's search path.

**Comment by panzergame** [comment]
Do you have the same issue with controller python module ?

**Comment by sdfgeoff** [comment]
No, the controller works from other paths.

**Comment by sdfgeoff** [comment]
I thought I'd clarify this some more:

[componentpathtest.zip](https://github.com/UPBGE/blender/files/648070/componentpathtest.zip)

In that zip, when you hit play you can see it running a function from the script in the scripts folder, but I cannot add a component from that same script.

**Comment by elmeunick9** [comment]
I've succesfully added search paths using a workarround and without any extra .blend. 

Basically you make a script with an event handler (on scene load for example) that adds your folder to the PYTHONPATH envoirment variable. This will work for when launching the game with the blenderplayer_start() operator. For the viewport and to find the components from blender, you need to use sys.path.append(path) (since python is already loaded and the env variable won't do anything).

However notice that for this to work once you export the game you will need a launcher that modifies the PYTHONPATH envoirment variable before launching the game. Having this fixed without a workarround would be better.

Actually, there is a related problem wich I think should take priority, and that is that python packges don't work. You should be able to import a component with a something like "scripts.com.ai.Player". If we had that we wouldn't need to add a system path to python except for shortening the namespace. 

Of course if we could have an easiest way to do it it would be better. Another problem is that packges don't work.

**Comment by panzergame** [comment]
@sdfgeoff : Could you confirm that 520d6bfb57556fd7a8906270751f5d3979d7282e fixed the issue ?

**Comment by sdfgeoff** [comment]
Yup. Works great. Thanks
