### ISSUE TITLE
Feature Request: Option to disable mist in viewport

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#337]
It would be great if you would add an option to disable the mist in the viewport. Because if you have a large map and zoom out you won't be able to see anything except the mist itself.

**Comment by youle31** [comment]
Hi, can't you disable the mist in the world panel? You mean add an option to disable the mist in viewport, but make it work in the game engine?

I automatically set new features requests in low priority because we have already ton of work. (If some feature requests seems to us easy to do and essential we'll do it quickly but it is not the case here)

**Comment by Momel15** [comment]
> Hi, can't you disable the mist in the world panel? You mean add an option to disable the mist in viewport, but make it work in the game engine?

Yes, that's what I mean. Thanks anyway :)

**Comment by youle31** [comment]
For the roadmap (It's possible that all this features won't be included in 0.1.3):
Merge 2.8 branch
Mesh batching [author=Tristan][time=2weeks](0.1.2)[ge_batch](delayed because of a bug for alpha meshes)
Per GPULamp unique dynamic uniform flag [author=Tristan][time=4days](0.1.3)
Game object layer for shadow casting [author=][time=3days](0.1.3)
Python addon include path in game [author=][time=1week](0.1.3)
Print support of ARB_geometry_program in PrintHardwareInfo [author=][time=20min](0.1.3)
Remove usage of DerivedMesh for render and physics [author= Tristan][time=2weeks](0.1.3)
Vibration actuator improvement[author=lordloki](0.1.3)
Avoid Cubemap rendering when cubemap object is outside camera frustum (at the previous frame) (I guess this will be quick to review)(youle) 
ge_eax to Python [author=Diego, Tristan][time=2days]
Planar reflections?
Area lights?

Else, I did the patch to disable mist in viewport but not in game engine, (ge_mistinviewport) but I don't know if it will be accepted.

**Comment by Momel15** [comment]
Thank you (for both the roadmap and your work)!

Didn't expect that you would do a commit for this request after your first answer, I hope it will be accepted :)

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.

**Comment by youle31** [comment]
panzergame added it in last master... This will be in 0.1.5

**Comment by Momel15** [comment]
Thank you! 👍
