### ISSUE TITLE
[Request]Joystick Sensor Events

### ISSUE THREAD

**Issue by N0Lif3** [UPBGE/blender#364]
I would like to see the Joystick logic brick Sensor gain the Events list that the Keyboard Sensor has.

bge.logic.getCurrentController().sensors["Keyboard"].events is a comprehensive list of every key that has been pressed, this includes multiple keys being held, and knows the status of the key (1 = just activated, 2 = active, 3 = just released). [Joystick].events would be a boon for scripters like me.

From what I can see on UPBGE, you've even gone as far as to remove basic scripting functionality that exists. See pic:
![hmmm](https://cloud.githubusercontent.com/assets/25230710/22120272/efe94d84-de33-11e6-9672-a4361adf08b9.png)

**Comment by panzergame** [comment]
@N0Lif3 : From what i see the first print represent the content of a list which is normal for logic.joysticks and too for BFBGE, but the second print look like the content of a sensor object. Are you using the same code in UPBGE and BFBGE here ?

**Comment by lordloki** [comment]
Using 
`import bge
cont = bge.logic.getCurrentController()
sen = cont.sensors["joystick_sensor"]
print(dir(sen))`
you obtain the same attributes than second console image. 
Some of them already deprecated (Hat related) and other has a constant value always (numButtons = 15, numAxis = 6). For your purpose you can use axisValue that is a list of 6 values (Left_Stick_horizontal, Left_Stick_vertical, Right_Stick_horizontal, Right_Stick_vertical, left_shoulder_trigger and right _shoulder_trigger) and activeButtons that is a list of 15 values point out which button is active.

I will commit in the next days a modification for activeButtons to return ['A', 'B', 'X', 'Y', 'START', 'GUIDE', etc] instead of [0, 1, 2, 3, 4, etc] to clarify better which button is activated.

**Comment by youle31** [comment]
Yes, I talked to @N0Lif3 yesterday on IRC. I think you make a confusion beetween python joysticks and joystick sensor.

You can find both API in help->python api reference typing SCA_PythonJoystick and SCA_JoystickSensor.

For sensors status, you can look here: https://pythonapi.upbge.org/bge.types.SCA_ISensor.html?highlight=status#bge.types.SCA_ISensor.status

**Comment by youle31** [comment]
Can I close issue?

**Comment by youle31** [comment]
By the way, @lordloki, didn't you removed hatValues, hat etc...? (It's still in the API)

**Comment by lordloki** [comment]
@youle31 I left them as deprecated, We can removed....

**Comment by youle31** [comment]
Ah ok so maybe the API is not up to date (I can't see the deprecated message). Or you added a message only when we use the code?

https://pythonapi.upbge.org/bge.types.SCA_PythonJoystick.html?highlight=hatvalue#bge.types.SCA_PythonJoystick.hatValues
https://pythonapi.upbge.org/bge.types.SCA_JoystickSensor.html?highlight=hatvalue#bge.types.SCA_JoystickSensor.hatValues

**Comment by lordloki** [comment]
I added a mesage when we use the code, a example:

> PyObject *SCA_JoystickSensor::pyattr_get_hat_values(PyObjectPlus *self_v, const KX_PYATTRIBUTE_DEF *attrdef)
> {
> 	ShowDeprecationWarning("SCA_JoystickSensor.hat", "SCA_JoystickSensor.button");
> 	return NULL;
> }

**Comment by youle31** [comment]
ah ok :)

**Comment by N0Lif3** [comment]
I'm sorry for appending irrelevant information in the second half of my post which led to a complete tangent about what I assumed was pulled from the engine

Back to the original point of my request, please. I would like to see the Joystick logic brick Sensor gain the Events list that the Keyboard Sensor has.

**Comment by youle31** [comment]
Answered on irc.

**Comment by youle31** [comment]
Sorry, I did my best saying that you had to look at SCA_ISensor, SCA_JoystickSensor, SCA_PythonJoystick APIs
