### ISSUE TITLE
Bug: Weird behaviour while merging trees

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#378]
test file: http://pasteall.org/blend/index.php?id=45270

- The trees appearance change while we are merging.

Remark: The more the mesh becomes bigger, the slower the merge is done. I guess this can be explained but as I didn't fully read batching code :P

**Comment by panzergame** [comment]
The issue about merging time is mostly fixed. The maximum time for me now is 1ms vs 13ms before.
About the appearance i think that vertex normals are odd. I'm debugging.

**Comment by panzergame** [comment]
The artefacts are caused by the render order of the objects. 
An issue about mesh sort for batching group is solved in b1069b84fede34e0d1a0d43d4573ebea70676a13, but the artefacts are still here even if they are less visible. The transparency batching mesh are rendered before all the other transparency mesh because it will be hard to find a way sorting the batching mesh and the other meshes. Even if a solution is found, what will be the interest ? The batching mesh could be a mesh around all the scene which will let the sort useless for it.

@youle31 : Let free to ask for details.

**Comment by youle31** [comment]
Oh great about loading time! This is really impressive. About the fact that the transparent batched objects are a bit different than when they are not batched, this is only a bit annoying when we merge objects to batch during runtime (or split I guess) because that generates a "visible" changement. But I let you decide if this is important enough or not. You can close the issue if you think it's ok (I guess this would be hard/slow to make a transparent sorting each frame inside the batched group...)

**Comment by panzergame** [comment]
The only solution to avoid these artefacts will be to split the batch group in multiple batch group to preserve the render order with other non batched meshes, this is very complex and, I think, killing the batch speed up. The same happen for GI…
I close then………
