### ISSUE TITLE
Possible logic% regression?

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#423]
Made a test with the game Nuke from bgmc 23. Modified only the constant materials on.
Possible logic% regression; img: http://pasteall.org/pic/show.php?id=113474
BF bge logic: 7% Master build: 14%

**Comment by ondredeniso** [comment]
the niggers can answer you. im ukrainian tatar

**Comment by ondredeniso** [comment]
better remaster load resource part for big games, because very slow loading.

**Comment by ondredeniso** [comment]
u here, bro? 0o

**Comment by ondredeniso** [comment]
im ukrainian tatar, i can only help u in our national idiological

**Comment by Akira1San** [comment]
What do you mean, have you tested too?

**Comment by Akira1San** [comment]
One more test/ image: http://pasteall.org/pic/show.php?id=113565
left upbge 015 modifier applied branch - logic 14%, right bf bge 268c - logic 6%

**Comment by youle31** [comment]
http://pasteall.org/299632
The main difference comes from the scene graph update once we call ApplyRotation

**Comment by Akira1San** [comment]
I see, so this was fixed behavior.

**Comment by youle31** [comment]
yes, a fix that costs a bit performances but was needed.
But in BF bge, I have 0.04ms, in upbge, 0.11ms, and when I comment NodeUpdateGS(0.0f); in upbge I have 0.06ms. So I don't know why we have 0.02ms more than in BF bge...

**Comment by panzergame** [comment]
@Akira1San : Did the issue still exist ?

**Comment by youle31** [comment]
@panzergame: The test file is here: http://pasteall.org/blend/index.php?id=45937 (picked in another Akira_san report). I test

**Comment by youle31** [comment]
@panzergame: But I confirm what Akira_san said (there is a difference beetween 0.1.2 and 0.1.5 than can't come from NodeUpdateGS iirc because the NodeUpdateGS patch was already in 0.1.2... So we'd need to check gitk, (or bisect which is very complex because we have to use MSVC 2013 and 2015 and checkout old libs...)

**Comment by youle31** [comment]
My results:
master: 1.02ms
0.1.5: 0.92 to 1.02ms
0.1.4: 0.82 to 0.93ms
0.1.3: same as 0.1.4
0.1.2: 0.76 to 0.82ms
with this test file: http://pasteall.org/blend/index.php?id=46189
like if there was 3 performances decreases... This would be very hard to solve. And maybe it doesn't come from upbge...

**Comment by panzergame** [comment]
Left UPBGE, right BFBGE:
![profiler_423](https://cloud.githubusercontent.com/assets/8046004/25781158/ff55fe46-3335-11e7-8a9f-e094bec605e6.png)


The difference in logic time is because of the object scene graph node update, but this update time is constant if you add the scene graph time and the logic time.

About the global slow down, it is introduced by the mesh polygon sort, #456 is already treating this subject.

**Comment by Akira1San** [comment]
This can be closed.
