### ISSUE TITLE
Bitmap texts: just to not forget

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#469]
https://blenderartists.org/forum/showthread.php?420410-Dynamic-bitmap-text-in-UPBGE
https://github.com/UPBGE/blender/commit/13abc6328c32a934053b9cdd6fa59092270db269#commitcomment-21835814

(I mark it as a bug just to not forget. I can try to restore it if you agree)

**Comment by youle31** [comment]
Voilà I restored it (it's dirt but it's just to open discussion): https://github.com/UPBGE/blender/pull/470

**Comment by panzergame** [comment]
I'm not very sure of what is doing the usage of image material for text. In the file example file the color of the text is not taken in account, and only the alpha channel of the image is used.
@youle31, @DCubix, @lordloki : What's the difference between a custom ttf file ?

**Comment by youle31** [comment]
I never used this feature personnaly so it could be good to have opinion of the ones who use it.

on the net, there are old topics talking about (http://www.blendenzo.com/tutColoredText.html...)

**Comment by haidme** [comment]
@panzergame - It can be used for custom letters or images(instead of letters), custom fonts with effects on letters(glow,outlines,gradients..etc). Also for animating(images) using keys as keyframes. That's the difference. You might be able to create images in a custom ttf font, but not glow and other effects. Also it is way harder, than just to edit a bmp image.
Overall it is not a huge feature, just I think it is nice to have it. It is not as flexible as ttf and has many limitations, like different language support, not textfields width out of the box and so on.
If someone is wondering how it works and looks, check my games - they all use this feature instead of ttf fonts.

**Comment by youle31** [comment]
Oh, I didn't even noticed that in the .blend, object color was animated (the logic bricks are missing)

**Comment by haidme** [comment]
Yep, you can also animate the material applied on the font.

**Comment by Akira1San** [comment]
If its using TexFace, the bf devs want to remove it. link: https://developer.blender.org/T51382

**Comment by youle31** [comment]
The feature is still in old bge. @panzergame : Did you included it in 2.8 upbge branch?

**Comment by panzergame** [comment]
@youle31 : For the moment no to limit compatibility between UPBGE and UPBGE 2.8 branch. I will work on this old feature later...

**Comment by youle31** [comment]
@haidme : Finally, as we go for very big changes when working on blender2.8, as this feature is badly documented, as it seems there are compatibility issues with some langages, and that the code seemed a bit old and doing a mix between blender sources and game engine sources (problem of design), as it's not a prior feature for the game engine, we won't restore it for now. It was interesting, but I think not important and used enough to be restored at the moment when we begin to work on merge upbge with 2.8. I'm sorry  to have make you waste your time. Maybe in the future we could do a work on texts to have a better control on it, and have the possibility to use materials with an easier approach (material for all texts) but it is not for now. Anyway, thanks to have showed this feature to us that we didn't know. I'm sorry that it will cause a problem to you if you try to port your game to upbge... :/ Bye!
