### ISSUE TITLE
Bug: 17th debugging session

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#478]
BGMC 23:
- Nuke/NUKE/levels/levelalley2.blend -> walk until you are taken by the police -> animation then crash
- The hole/main_game.blend -> press P -> this exits bge immediately

**Comment by youle31** [comment]
For the first bug, this: http://pasteall.org/382131/diff seems to avoid the crash. Indeed when replacing KX_Scene, the old was calling KX_Scene destructor and m_animatedlist->Release(); was called. Then I think the new scene was trying to add m_animatedlist->Add(gameobj); whereas m_animatedlist had already been removed... I'm not sure of the fix but it seems to avoid the crash

**Comment by youle31** [comment]
For the second bug, it seems related to new events system. It didn't worked in 0.1.5 neither in 0.1.6. The python script throws an exception and endgame when there is a problem. So I think we can accept this little backward compatibility issue and let the user adapt his event manager with new upbge system.

**Comment by panzergame** [comment]
@youle31 : For the first bug can you try the branch ge_animation ?

**Comment by youle31** [comment]
@panzergame : It's ok :)

**Comment by panzergame** [comment]
For the second report it's because the user us the raw value of the enum for key ESC (in game_input.py), previously it was 130 but with the new event system some of the unused enum where removed and the other shifted. I can restore the number, but in this case it will break the file using the same dirty method currently running in UPBGE...

Anyway this method is strongly deprecated.

**Comment by youle31** [comment]
ok. So feel free to close when you want.
