### ISSUE TITLE
Change object names with Python at runtime

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#52]
It would be great to have a Python command to change an object name.

That would be helpful if you want to add objects with `addObject` and change their attributes, because they all have the same name so `scene.objects` won't work for this purpose. With such a command you could edit the name directly after  #adding them and edit other attributes later on or in another script.

What about `object.name = "insertANameHere"` ?

**Comment by panzergame** [comment]
Yes using the same name can cause problems, but it's very useful for groups. For example you have a group which contains objects named "A" and "B" if you duplicate this group you will want to access to this group object with the name "A" and "B".

A solution is to add an other name variable, or simply store the pointer returned by addObject.

**Comment by Momel15** [comment]
Implementing this command doesn't mean that you _have to_ use it. If you want to use groups you don't have to. But for some functions it would definitly be very helpful.

Just to be sure that you know what I'm meaning: I don't mean that `addObject` should rename all the added objects automatically. I mean that you could implement a command which can do this.

**Comment by panzergame** [comment]
Ok, my bad. But it will break some commands which use object's names, e.g:
sce.addObject
obj.reinstancePhysicsShape
ect..

So the solution is to change the name in converted object name lookup table, or allow the user to only modify name of duplicated objects.
@Momel15 : What's the best for you and other users ?

**Comment by Momel15** [comment]
I'm not a dev (and also not a native english speaker) so I don't know what the/a lookup table is, but the second approach sounds promising to me.

**Comment by panzergame** [comment]
At the conversion time we store each object with it's name in a list. This list is used for functions which can use name instead of object pointer (addObject ....)
So here each duplicated objects can be used with only name in addObject (normal...) reinstancePhysicsShape ect... because they are not in the name list.

**Comment by Momel15** [comment]
Thank you for the explanation :)

I still think that the second solution is sufficient, but how about asking other users? (I don't know the pros and cons)

**Comment by youle31** [comment]
@panzergame: Finally, I think it's feasible because scene.objects list already contains instances list (when you add 10 cubes to scene and print scene.objects, you can see the 10 instances). So changing the name of 1 instance is not a problem, unless I'm missing something. I'll do the patch and we could discuss it.

**Comment by BluePrintRandom** [comment]
Many game engines generate a UUID for each added the object,

**Comment by panzergame** [comment]
Done : afeaaa9cfd6b2f8478d6f56815b77204690970b8
