### ISSUE TITLE
[Request] Set filter and clamping for textures

### ISSUE THREAD

**Issue by HG1-Public** [UPBGE/blender#525]
Actually you only can overwrite the filter and clamping type by using the bgl wrapper.
Changing the clamping type can avoid seams or allows to place a non repeating texture (decal).
glBindTexture(GL_TEXTURE_2D, id)
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER)
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T,GL_CLAMP_TO_BORDER)

Some time ago I have done a decal patch, where it was possible to switch between clamped to edge an repeated in the blender UI. The patch is out dated and can't be applied any more.
https://www.dropbox.com/s/o4rfdz8yz0pceqk/decal2.patch?dl=0

Also setting the filter type for the texture is sometimes necessary for some shaders.
I already hade some problems with the linear interpolated textures or frame buffer.
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST)
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST)

I personally can deal with the bgl wrapper solution.
But maybe for other users it would be a good idea to add it to the UI and/or add an API to set this for the textures and the frame buffer.

**Comment by youle31** [comment]
Hello, currently we work on 2.8 branches. This is still unstable. When we'll have a solid base to work with, if @panzergame is ok, he could give you commit rights to make branches to improve KX_2DFilters API (I already updated 2D filters for core profile (the only changes are that you need to write: in vec4 bgl_TexCoord; instead of gl_TexCoord[0] and out vec4 fragColor; instead of gl_FragColor)).

You can connect on #upbgecoders if you want to discuss about it but panzergame is a bit busy these days.

Else if you want to contribute to 2.8 transition, you are welcome too if you have ideas.

Anyway, once bge/upbge will be merged in 2.8, I guess we'll work on phabricator and as you already have commit rights in bge, you'll have the possibility to contribute directly on phabricator (but we don't know when the merge will happen).

So if you want to contribute before merge, we can ask panzergame for commit rights, else after merge this will be possible without doing anything. It's as you like.

About clamping/add filter modes for textures, there's no problem for me if it's usefull for you.

**Comment by panzergame** [comment]
@HG1-Public : Eevee image node allow to select some wrapping texture mode (maybe in shader side, have to check):

![2017-07-09-161525_2646x1024_scrot](https://user-images.githubusercontent.com/8046004/27993825-5c2cec72-64b1-11e7-9f1d-e20e8b7d357e.png)

**Comment by youle31** [comment]
Parenthesis (@solhrdulik69: Could you explain what's wrong with my answer instead of adding emoticons that means nothing. I work for free. I'm not decidor. I propose to panzergame to give @HG1-Public  commit rights... So what's wrong? Anyway, I blocked your notifications to not be annoyed with you but I can see your answer.)
