### ISSUE TITLE
bgl_RenderedTexture (and it's mipmaps) in non-filter GLSL shader?

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#527]
Is it possible to use bgl_RenderedTexture (including textureLod() functionality) in a GLSL shader which is not a 2D filter? If it is possible, than I would be happy to find out how. I can think of using a 2D filter, getting it's offscreen and using that as the texture input in the GLSL shader, but in my opinion that's an unnecessary sample of a 2D filter.

P.S. If it's not possible, don't bother with stuff like this before Eevee thing is done :wink: 

P.S.S. The bad thing I noticed is that you can't use setTexture() with texture bind codes in non-filter GLSL shaders :cry:

**Comment by panzergame** [comment]
The easiest (and maybe the only) way is to do a texture copy indirectly by the filter rendering, because when the shader will be used the render texture you want to use is the one currently rendered and doesn't have the result of the last frame (the only result you can get) because of the background clear and rendered objects previously.
