### ISSUE TITLE
UPBGE - Eevee Volumetric Branch, crash into Runtime

### ISSUE THREAD

**Issue by RodrigoMedeirosrRS** [UPBGE/blender#567]
Hello people!

First, i wanted to congratulate your initiative! I really believe that the combination of Eevee render with the BGE has the ability to radically change the way we indie producers create our games!

Now to the point, I compiled yesterday a version of UPBGE present in the Branch Eevee Volumetric, then i copy all the standard's addon of UPBGE 1.9 for the compiled version, and tried to export the project to runtime.
![export](https://user-images.githubusercontent.com/7956669/29496557-4b2e074c-85ab-11e7-84df-21bfd3f24d28.png)

Inside the blender everything worked perfectly, but in the exported version, he crash when starting. Any tips how I can solve this problem?

Note: I know a few things about python and lot things about c ++, so i can try to fix the problem at the code level if you can tell me where to start. I'm also very good with post-processing filters, I can help create new filters for BGE, but I'd need to know where exactly the code gets in the filters.

**Comment by youle31** [comment]
Hi, I'm sorry but this is too early for eevee in upbge. We just begun to work on it. It is very unstable, it doesn't work with blenderplayer (so no possibility to export game neither). Both eevee (viewport engine) and upbge are in the early stages of development. I think it will be available in 2018 but I can't tell when exactly.

Some things are working on my computer but there are many crashes, so I didn't do any release. I don't even know if the main upbge developer can run eevee_volumetrics branch.

So for now we can't do nothing, and we'll accept issues only when we'll have published the first release on upbge website because we have important things to fix first.

If it's just for testing purposes, for reference, my config is GTX 970, Windows 10 64, Visual studio 2013 and I build in 32 bits. I can't say if it works on other machine than mine...
