### ISSUE TITLE
Bug: BGMC 24 Manic macks

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#591]
controls are not responding

**Comment by panzergame** [comment]
Fixed in master.

**Comment by youle31** [comment]
for me it doesn't work as before

**Comment by panzergame** [comment]
`SCA_KeyboardSensor.inputs` was a list but this was inconsistent with SCA_PythonKeyboard. it was replaced to a dict after 0.1.9.

`SCA_KeyboardSensor.events` is left to list because it will break compatibility with BFBGE game whereas `SCA_KeyboardSensor.inputs` breaks compatiblity with only UPBEG games.

@BPR: You should update your scripts please.

**Comment by youle31** [comment]
Ok, so all is right here, it's just a minor backward compatibility issue. Thanks panzergame for clarification
