### ISSUE TITLE
Hue and Saturation for Textures

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#613]
Hello! I would like to propose a feature request (and a discussion as well for this feature).

Currently, it's possible to colorize textures to a new color easily through 'Object color' in Materials tab and setting the object color in Object tab. It's useful, but is too limited and don't look good in most of cases.

Imagine the case where you have a detailed character's shirt, with a color and a white logo. If you want different colors for the shirt without affecting the logo you will have to add different textures with the desired colors (bigger game size and limited colors), or use two materials (one for the shirt and one for the logo), and the shirt material would have the 'Object color' property marked to follow the color of the object (too complicated, with optimization threatened due to more materials in game). This last case would get worse if the shirt have different colors, like a flowery shirt, where the 'Object color' option would change all the colors to one equivalent (like red or blue, for example), not keeping the contrast between the colors.

This lead me to think: is possible to create a hue / saturation for textures to use in BGE (with realtime change support, like the 'Object color' option)? This could be a life saver in a lot of cases, like the related one.

Watch this example made by me to see exactly what I mean about the hue / saturation feature and see how it could be useful:
https://www.youtube.com/watch?v=97917orJ3c0

Thanks. :smile:

**Comment by Jesusemora** [comment]
i don't think it's necesary. you have 4 values in object color (red, green, blue and alpha). you can connect the object color values to a colorramp node with all the colors you want in node editor, use the textures as value for mixcolor, mix all the textures, and THEN connect it to a material node. the lights are calculated once because you have a single material, and performance is the same.
you can have 3 colors to combine with the diffuse. if you want more details, you divide the character into diferent parts, different objects with their object colors. look at how games do that, they never have more than 3 or 4 colors to combine.

**Comment by joelgomes1994** [comment]
Damn, I forgot about nodes! I think I should be a little more aware before creating a new issue. :smile: 
See my blend files of hue changing using nodes and Python: http://pasteall.org/blend/index.php?id=48049
However, it's quite complicated for someone who doesn't know Python. Close the issue if you think it's irrelevant. ;)

**Comment by joelgomes1994** [comment]
Although it would be good to have a Game Property input node too, to aid this and a lot more tasks.
