### ISSUE TITLE
ge_mathfu debug infos win32

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#624]
compilation log: http://pasteall.org/638982/c
warnings/errors: http://pasteall.org/638991/c
blender.exe -d: http://pasteall.org/638995
(The compilation succeed)

but this is crashing with default cube in release mode

**Comment by youle31** [comment]
@panzergame : For the bug with sortPolygons, I can reproduce it in this file: http://pasteall.org/blend/index.php?id=48164

**Comment by panzergame** [comment]
I checked recently with my test files (~300 files from https://github.com/UPBGE/testfiles), i fixed the issue noted and reported the issue common with master (only 2).

@Akira_San: You talked about an issue with a mouse look script, could you provide your example file please ?
@youle31: Could you test on windows with your test files please ?

If everything goes right, i would like to merge the branch tonight.

**Comment by Akira1San** [comment]
The file: https://drive.google.com/open?id=0B6yNvVGWiWysRWtKcWxILTVtV2M
The bug starts from upbge 008 where the camera position changes compared to 007 and bfbge, and in mathfu the camera drops to the ground.
In the game BGMC 23 Onikiri Demon slayer the char can stuck or do some strange rotate when you move the mouse around.

**Comment by youle31** [comment]
hello, I tested with some of my files.
I confirm the bug with alpha sort is fixed.
I have an issue in this file with controls: https://drive.google.com/file/d/0B3GouQIyoCmra3IyT1VkVXBxUHM/view?usp=sharing
steps:
- press P in dark_war.blend
- move with W and mouse for mouselook
>> Sometimes the view begins to flicker for me
(note: in master this doesn't flicker, but I noticed a different behaviour since last time I tested the file)
(note2 (for myself): not related to mathfu, but parallax seems broken in some files)

**Comment by panzergame** [comment]
@joelgomes1994: It looks that ge_mathfu is not working in your Dark War project. Can we know what are you using to control the camera ? A mouse look with a script for collisions ?

**Comment by panzergame** [comment]
@youle31, @Akira1San, could you please provide a copy of the current ge_mathfu build to @joelgomes1994 please ?

**Comment by Akira1San** [comment]
link; https://drive.google.com/open?id=1Y4WR6GEbXdiGyxszUYEOI2Z9thotJ7TH

**Comment by joelgomes1994** [comment]
@panzergame , @youle31 
Oh man, I'm so sorry, my Github notifications were off, I've just discovered you mentioned me because I was passing by reading issues. I've turned it on, I hope to get the notifications now.

- My mouse look is a mix of Mouse actuators with it's settings changed through Python.
- The camera collision is made through a set of empties with specific functions, and one of them casting a ray to another to check obstacles.
- The laser point actually flickers when you don't move the mouse because I've changed the skippedTicks of the always sensor to a higher number (one performance measure, but doesn't worked as intended).

I just switched my master to the ge_mathfu branch, and I'm building right now and I'll test the Dark War project to see the reported issues.

**Comment by joelgomes1994** [comment]
I have no issues in Dark War using ge_mathfu build, works exactly as in master. I haven't seen any of the reported issues in the game.

> Sometimes the view begins to flicker for me
(note: in master this doesn't flicker, but I noticed a different behaviour since last time I tested the file)

**Comment by panzergame** [comment]
@youle31, @Akira1San : No more warning on MSVC about alignment, isn't ?

**Comment by Akira1San** [comment]
No warnings.

**Comment by youle31** [comment]
Hello, no, I didn't noticed new warnings when compiling. I did quick tests of the last master and opened some bug reports. I don't really know if it is bug or deprecated errors. I can't check for now.
