### ISSUE TITLE
Severe slowdown in scenes with lots of moving objects

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#65]
Tested with build 243da53.  In UPBGE, moving lots of objects is about 3x slower compared to upstream.  In my test I used 800 moving + rotating cubes.

Test blend: http://www.pasteall.org/blend/41135

Profile:
```
BF + VBO:
57ms total
3ms logic
50ms scengraph

UPBGE + VBO:
141ms total
138ms logic
0ms scenegraph

BF + VA:
34ms total
2ms logic
29ms scenegraph

UPBGE + VA:
149ms total
145ms logic
0ms scenegraph
```

**Comment by youle31** [comment]
Hi, I think this is because of this commit: https://github.com/UPBGE/blender/commit/5316707ffb315f047f8055c66e037367fdcb29ec

pqftgs: could you confirm by commenting NodeUpdateGS in ApplyMovement and ApplyRotation (in KX_GameObject.cpp)

Before this commit, the position of the gameobject in the scenegraph when you used applyMovement and applyRotation python method was updated 1 frame too late. So I don't think revert this commit is the solution. But if the position of the object is updated twice, maybe we could remove a call to NodeUpdateGS and get the same performances as before the commit.

**Comment by pqftgs** [comment]
Yes - that reduces the frametime from 150 -> 100.  However, it is still 2x slower than BF.  Also I do agree the 1-frame delay is really annoying.

**Comment by pqftgs** [comment]
Nevermind, the 2x slowdown also occurs in my recent 2.77 build - so that is unrelated (Is anyone else having that issue btw?)

**Comment by Akira1San** [comment]
Hmm i dont see a thing, when i press  p key. Used blender 2.77.

**Comment by panzergame** [comment]
Apparently this is a compilation issue, pqftgs had the same result with a self compiled BF BGE.
@pqftgs : can you add more details on the problem ?

**Comment by pqftgs** [comment]
Fired up my crusty old Windows today.

@Akira1San: At least in 2.76 it seems module mode is broken on Windows.  Can anyone confirm?  Should open a new issue if so.

@panzergame: The BF Windows build was even slower than my custom builds, so I will blame BF Linux64 for being too fast.  Probably CPU cache optimizations or something.  Gonna put that on the backburner for awhile.

Back on topic:  There is still waste re-running NodeUpdateGS, but I don't wanna go back to the hell that was everything being delayed 1 frame.  Hmm..

**Comment by panzergame** [comment]
I cannot reproduce the bug with a non bugged action: obj.worldOrientation

BF BGE:
total = 90
logic = 84
scenegraph = 1.26

UPBGE:
total = 86
logic = 80
scenegraph = 0.90

test file = http://www.pasteall.org/blend/41217

If we assume that apply[Movement/Rotation] is slower now because it request a position/rotation update, apparently there's nothing more.
Also the scenegraph time in BF BGE was certainly caused by the update of the position in node update and not just after python call.

@pqftgs : Can you confirm that you get the same results ? If yes close the issue.

**Comment by pqftgs** [comment]
I see now.  The original applyMovement/applyRotation was faster because it was bugged.  The problem is that calling multiple (unnecessary) node updates per frame causes significant performance loss.  I will have to work on a solution for my game, but since this isn't technically a regression I will close the issue.

**Comment by panzergame** [comment]
@pqftgs : we can't remove this call because the user want to access to the new position after apply[Movement/Rotation]
