### ISSUE TITLE
the ingame python console won't start and crashes the game

### ISSUE THREAD

**Issue by Anarchokawaii** [UPBGE/blender#693]
1. i enabled python console in game 2. started game 3. hit the keys 4. and then blender freezes. i try hitting the escape key but nothing happens and the only way to get out is by killing the process.

**Comment by BluePrintRandom** [comment]
if you use the console you have to quit it with escape

On May 22, 2018 8:20 PM, "Anarchokawaii" <notifications@github.com> wrote:


   1. i enabled python console in game 2. started game 3. hit the keys 4.
   and then blender freezes. i try hitting the escape key but nothing happens
   and the only way to get out is by killing the process.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UPBGE/blender/issues/693>, or mute the thread

**Comment by Anarchokawaii** [comment]
i did do that. it doesn't do anything. blender just freezes when i start the ingame console.

**Comment by BluePrintRandom** [comment]
I use it all the time on windows,

if I click the console and type, and click back on blender and quit, it
appears hung up, unless I mouse back to the console and hit esc.

**Comment by Anarchokawaii** [comment]
the console doesn't even appear. it just freezes the game. and you know what console i am talking about right. the ctrl+alt+shift+t console. i am using windows.

**Comment by lordloki** [comment]
It works perfectly in master. I point out a little tutorial to launch the interactive python console

![1](https://user-images.githubusercontent.com/1015605/40510603-7db7ec56-5f9d-11e8-9159-310819b1cbfd.png)
![2](https://user-images.githubusercontent.com/1015605/40510609-843da28c-5f9d-11e8-83bb-e2aa6644bee0.png)
