### ISSUE TITLE
KX_Camera.getScreenRay not working if cam is Ortographic

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/blender#765]
This function:
https://pythonapi.upbge.org/bge.types.KX_Camera.html#bge.types.KX_Camera.getScreenRay

Doesn't work if the camera are Ortographic. I made a small example:
http://pasteall.org/blend/index.php?id=50026

Press P and nothing will happen. But if you change the camera mode to Perspective and then press P, if you mouse over the cube it will start rotating (what I programmed to do).

This function is very important right now, since we will not have logic bricks to get the mouse over object and things like this. 

Thanks! :smile:

**Comment by panzergame** [comment]
`getScreenRay` is using internally `getScreenVect`which from the code and documentation just computes an un-projected point in view and get the vector from the camera origin to this point. Then this vector is used as ray cast direction and the ray cast always start from the camera origin.
Such behaviour is appropriate only for perspective camera.

The idea to solve this issue is to forget about getScreenVect in getScreenRay and instead un-project two points to compute the ray direction and use the first for the ray origin.

Is this solution acceptable ?

**Comment by UnidayStudio** [comment]
@RomStef the problem is when you're not using logic bricks.

@panzergame Yes. But from the point of view of the user, the best option is to automatically decided what solver to use (one for the perspective camera and other for the ortographic) inside the getScreenRay (or inside the getScreenVect). By doing this, the user (that in most case will not know the math behind the scenes) will not have to care about this and will be able to use these functions no matter if the camera is ortho or persp.

**Comment by panzergame** [comment]
@UnidayStudio : The two points solution is general to any kind of cameras and could be optimized in case of perspective camera by using the camera origin as first point to get the ray direction.

Concerning getScreenVect, the documentation is:
```Gets the vector from the camera position in the screen coordinate direction.```
And this is applied properly currently even if it is not interesting for orthographic as the camera is not a "pyramid".

**Comment by UnidayStudio** [comment]
@panzergame ok! :)

**Comment by panzergame** [comment]
Fixed in #781.
