### ISSUE TITLE
Constant values for material shader.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/blender#81]
With the come of textures uniform youle and i was thinking about add an option in the UI to use constants values in the shader instead of dynamic uniforms.

I already made a commit about in ge_texture, but i'm really not sure about the name.
This option should be named ?:
- Dynamic Uniform(s)
- Constant Value(s)
- Use Uniform(s)
- Use Constant(s)
Also it should be plural ?

An other point of this issue is for the material, indeed currently they get the same issue that for textures. I propose to add two UI option, the first to use constant material setting values in the shader and the other to use constant light values:
- Constant Value (or the proper name found also for texture):
- ------- Material
- ------- Lamp

@DCubix, @youle31, @pqftgs, @Akira1San: What do you think about ?

**Comment by youle31** [comment]
panzergame: When you merged ge_texture branch, you didn't commited the commit that removes if (mtex->fac == 1.0f) fac = stencil. It's to make your work easier when you'll work on constants? Because for the moment, most of the attributes doesn't work because of this limitation...

Otherwise, if your performances tests on only 3 textures shows that there is a performance difference beetween with constants/without, I agree to make this patch and if we do the same for lights uniforms and all groups of uniforms, this could add a significant speed up to the upbge.

About the name, for more simplicity, i'd use "dynamic uniform" or "use uniform" unchecked/set to false by default. Why? because:
1) you don't have to add something in "bke_create_material" or such function to say that the flag must be to True when you create a material
2) For the existing material, at the start of Blender (on the cube), you don't have to add something in versionning defaults
3) No need to make versionning upbge too (I think)

**Comment by panzergame** [comment]
@youle31 : Are you sure to set "use uniform" to false as default ? I prefer to keep compatibility from old file and don't ask to the user to check an option in file loaded in new UPBGE version. And it's why i was proposing "use constant.."

**Comment by panzergame** [comment]
Also yes, i removed "(mtex->fac == 1.0f)" for this new patch.

**Comment by panzergame** [comment]
Ok, my first time test are with a 3 textured material and 5 point lamps:
Normal : 233ms
Constant Material and Lamp: 177ms

24 % faster

**Comment by youle31** [comment]
Yes I think it would be better to have the default mode to the one which is faster. Users would have to check manually what variable they want to change in realtime. If all options are dynamic uniforms by default, the users will have to uncheck too much things... I think. But yes, it's true, it will break the compatibility with materials that already use .diffuseColor API or such things.
