### ISSUE TITLE
New GUI , Personal consideration

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#867]
i think the new GUI is too confusional. In my opinion , the sections must be organized to show the topmost information about the work we do. Blender interface is not predispose to programming. you can write little script of course but the most of work you can do in the notepad++ as well. maybe on the second monitor. the outliner list is important for switching objects and layers in the scene, the properties tab have a lot of information we need. i think we should take more space for showing this two sheets. Another problem is switch in the uv editor for baking texture during the modeling phase.We can also use the space in the top right corner to show the camera view wen we can play the bp.exe . I have saved a startup file with a GUI dispose as shown in image.

![interface](https://user-images.githubusercontent.com/20901566/46472447-7c2fb000-c7dd-11e8-937a-ceb9f55c3bf7.PNG)

**Comment by EndSSgamesStudio** [comment]
I agree, these changes in layout are much better!

I do not like the current one, but, we can easily change the layout and by default...
but we have to think about the people who will know the UPBGE
**I do not think it's right to put the python area on display, people who start using UPBGE and see this, it will seem very complex and difficult to create a game...**

I also have a suggestion to change the theme to this: 
http://www.mediafire.com/file/76a2l3lypbufpch/Theme.xml/file  
Note: this theme was made by me, so it's okay to use

![abc](https://user-images.githubusercontent.com/35436445/46563960-e0846980-c8da-11e8-9083-8093d4c7db2c.png)

I also think that you should change the exit key to F1 or other
because it is common to use the ESC key as game menu and etc...

_Another interesting thing is that it would also be nice if you had a first-person character set up and not just a cube on the scene..._

**Comment by vlad1777d** [comment]
BTW, I made a much clearer interface theme that default one, if somebody needs.

![screenshot from 2018-11-02 03-10-06](https://user-images.githubusercontent.com/12682937/47888360-d3f91f80-de4c-11e8-97af-5143d1eb4c5e.png)

[morning_shadows_61.xml.tar.gz](https://github.com/UPBGE/blender/files/2540681/morning_shadows_61.xml.tar.gz)

**Comment by BluePrintRandom** [comment]
the only thing I don't like is the model selection color (blue) is near the
same as the background,
I love the text editor being dark, it is much much nicer on the eyes.

**Comment by vlad1777d** [comment]
@BluePrintRandom , I use dark themes from that times I began writing code.
Really it less strains eyes.

Feel free to fix it =)
Personally I like such color mixing =)
I correct theme every time I work with Blender.

**Comment by youle31** [comment]
As we can easily tweak and save our own UI preferences (File > Save startup file), and as i'd like to clean a bit the bug tracker to focus on bugs, I close this.
