### ISSUE TITLE
crash in new scene

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#876]
Hi guys , The program crash when i add a new lamp object(i have tried with an emission light lamp) in a new scene. 
In the attached file , just switch to upbge and add an emission light lamp

[crash.zip](https://github.com/UPBGE/blender/files/2456077/crash.zip)

**Comment by panzergame** [comment]
The steps to reproduce the bug is unclear for me:
 - by add a lamp object, you mean in game or in editor, i deduced that was in editor as you have none logic set.
- emission light lamp, you mean hemi lamp ?

I tested your file by doing:
- switch render engine to UPBGE in scene GUI
- in editor:
-    add hemi light
-    add point light
-    add spot light

And all worked fine. But as linux less frequently raises errors related to memory, @lordloki, @youle31 Could you please this file in windows ?

**Comment by RomStef** [comment]
Yes, in the editor and yes,adding an hemi. I have  the  win64 version.

**Comment by lordloki** [comment]
Confirmed. Also related to new OpenColorIO library. Compiling WITH_OPENCOLORIO = OFF solves this crash and the UV export one.
I'm trying to get a build using old lib.

**Comment by lordloki** [comment]
To be more explicit, the crash doesn't came from adding the lamp. It cames from adding the lamp then in the preview lamp windows it is rendered a preview -> calling OpenColor function --> crash

**Comment by BluePrintRandom** [comment]
are we ready to close this?

**Comment by lordloki** [comment]
Yes, i will control the crash resolution by the uv export layout crash issue.
Thanks for reporting.
