### ISSUE TITLE
Upbge 0.2.4 slow performance compared to 0.2.3

### ISSUE THREAD

**Issue by costantan** [UPBGE/blender#961]
At 0.2.4, when trying to record standalone or embedded player with screen recording software (Bandicam) game  speed is slowing down. This was not happening at 0.2.3 , framerate just dropped but overall game speed was not affected. 
Also, game speed is reduced from standalone player compared to embedded player. At 0.2.3, there was only framerate drop but speed was not affected.

Pc specs:
HP 8300 CMT, Cpu i3 3220, Ram 8GB, Gpu GT1030, Hdd SSD 500 GB and SATA 1TB

**Comment by RomStef** [comment]
I have the same issue on my laptop intel i7 7400, 8gb ddr3 and nvidia gtx950m . Try to remove the vSync option in the render panel. you can find a benefit even with AA = 16x and full hdri setting on

**Comment by panzergame** [comment]
Could you provide example files ?

**Comment by lordloki** [comment]
@panzergame, I think it is related to the commit that wait until next frame doing nothing to avoid stressing CPU.
From that commit I never get 60fps, always around 58-59fps.

**Comment by youle31** [comment]
yes me too. I think we should maybe do something with that because having 58/59 fps instead of 60 is causing few lags/displays issues too on my computer. Maybe it comes from that my screen refresh frequency is 60hz (60 images per seconds) and the framerate is slightly <.

I tag it as a bug

**Comment by JJGamerDe** [comment]
since I moved to 0.2.4 the UPBGE was very uncommitted, with problems in physics and etc.

**Comment by UglinessInTheUI** [comment]
2.79b is holding 60 fps solid. UPBGE is doing a solid 58 fps. Definitely a few new bugs in UPBGE.

**Comment by youle31** [comment]
58 fps instead of 60 is "normal" in upbge 0.2.4 because there was a commit to make the CPU sleep until next frame when vsync is enabled and use framerate is enabled. But we didn't managed to have exactly 60 fps. Depending on CPU, scenes... you can have 58fps, 59 fps but this is the intended behaviour. The bug is if it causes sync issues with screen refresh frequency... Anyway, the project is paused for now / and maybe it won't be continued. Then I think for now, users should choose the upbge version they are the most comfortable with, not necessarly 0.2.4. It can be 0.2.3. Personnaly, I like 0.1.7

**Comment by UglinessInTheUI** [comment]
Can you show me where is in the code that problem please ? Like , which page and what line number do i have to change in the source code ? Thanks. 

PS: Or a link to that commit so i can figure out what i need to change to change it back in a local build.

**Comment by youle31** [comment]
e9b07807f99d97dde7162b3fbb7439ea70fea0b5

Comment this:

http://pasteall.org/1509405
